src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>NumberofLocations__c</fullName>
        <label>Number of Locations</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PAN_Card__c</fullName>
        <label>PAN Card</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MyvalidationruleController.cls
public class MyvalidationruleController {
  Account account;

  public PageReference save() {
    try{
        update account;
       }
    catch(DmlException ex){
        ApexPages.addMessages(ex);
       }
    return null;
  }

  public String getName() {
    return 'MyvalidationruleController';
  }

  public Account getAccount() {
    if(account == null)
      account = [select id, name, numberoflocations__c,PAN_Card__c from Account
        where id = :ApexPages.currentPage().getParameters().get('id')];
      return account;

  }
}