src/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>country</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Employees__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>city__c</fullName>
        <label>city</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>deptno__c</fullName>
        <label>deptno</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>salary__c</fullName>
        <label>salary</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Employees</label>
    <nameField>
        <label>Employees Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Salary__c.object
<CustomObject>
    <description>This object defines the salaries of the employee</description>
    <fields>
        <fullName>Employees__c</fullName>
        <label>Employees</label>
        <referenceTo>Employees__c</referenceTo>
        <relationshipLabel>Salaries</relationshipLabel>
        <relationshipName>Salaries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>country__c</fullName>
        <description>This field defined the country list.</description>
        <label>country</label>
        <picklist>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austalia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uganda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singapore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Malaysia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pakisthan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Salary</label>
    <nameField>
        <label>Salary Range</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TrainingTest__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>TrainingTest</label>
    <nameField>
        <label>TrainingTest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>training test</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/wrappertodisplayIntandStringclass2.cls
public class wrappertodisplayIntandStringclass2 {
public List<wrapper> lstw = new List<wrapper>();
List<TrainingTest__c> lstTrain =new List<TrainingTest__c>();
List<Employees__c> lstemp = new List<Employees__c>();
public List<wrapper> getlstwrapper(){
lstTrain = [select Id,name,city__c,country__c from TrainingTest__c];
lstemp = [select Id,name,salary__c,deptno__c from Employees__c];
for(Integer i=0;i<lstTrain.size();i++){
lstw.add(new wrapper(lstTrain[i].name,lstTrain[i].city__c,lstTrain[i].Country__c,lstemp[i].name,lstemp[i].Salary__c,lstemp[i].deptno__c));
}
return lstw;
}

public pagereference doDelete(){
List<String> lsttrainnames = new List<STring>();
List<String> lstempnames =new List<String>();
for(wrapper w : lstw){
if(w.ischecked==true){
lsttrainnames.add(w.tname);
lstempnames.add(w.ename);
}
}
system.debug('****lstTnames***'+lsttrainnames);
system.debug('****lstEnames***'+lstempnames);
List<TrainingTest__c> lstTdel = [select Id,name from TrainingTest__c where name in : lsttrainnames];
delete lstTdel;

List<Employees__c> lstEdel = [select Id,name from Employees__c where name in : lstempnames];
delete lstEdel;
pagereference ref = new pagereference('/apex/wrappertoDisplayIntegerandString');
ref.setredirect(true);
return ref;
}
public class wrapper{ // wrapper class
public String tname{get;set;}
public String tcity{get;set;}
public String tcountry{get;set;}
public String ename{get;set;}
public decimal esalary{get;set;}
public decimal edeptno{get;set;}    
public boolean ischecked{get;set;}
public wrapper(String tname,String tcity,String tcountry,String ename,decimal esalary,decimal edeptno){
this.tname=tname;
this.tcity=tcity;
this.tcountry=tcountry;
this.ename=ename;
this.esalary=esalary;
this.edeptno=edeptno;
ischecked=false;
}
}
}