src/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>country</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Registration__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactNo__c</fullName>
        <label>ContactNo</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PersonName__c</fullName>
        <label>PersonName</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Registration</label>
    <nameField>
        <label>Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>registration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RegistrationClass.cls
public with sharing class RegistrationClass {
    public Registration__c objR{get;set;}
    
    public RegistrationClass(){
        objR = new Registration__c();
    }
    public pagereference doSave(){ 
            
            objR.PersonName__c = objR.PersonName__c;
            objR.City__c = objR.City__c;
            objR.Country__c = objR.Country__c;
            objR.ContactNo__c = objR.ContactNo__c;
            insert objR;
        return (new pagereference('/apex/registrationpage').setredirect(true));
    }
}