src/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>country</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TrainingTest__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>TrainingTest</label>
    <nameField>
        <label>TrainingTest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>training test</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Insertclass.cls
public with sharing class Insertclass {

    public String tCountry { get; set; }
    public String tCity { get; set; }
    public String tName { get; set; }

    public PageReference doInsert() {
        TrainingTest__c objTrain = new TrainingTest__c(name=tName,city__c=tCity,country__c=tCountry);
        insert objTrain;
        pagereference ref = new pagereference('/apex/insertingrecords');
        ref.setredirect(true);
        return ref;
    }

   
    
}