src/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>country</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DataLoad__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>city__c</fullName>
        <label>city</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>personname__c</fullName>
        <label>personname</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>DataLoad</label>
    <nameField>
        <label>DataLoad Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DataLoad</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/picklistvalueselection.cls
public class picklistvalueselection {
public list<selectOption> lstnames = new List<selectOption>();
public List<selectOption> getnames(){
lstnames.clear();
lstnames.add(new selectOption('--None--','--None--')); 
for(DataLoad__c objDL : [select Id,personname__c from DataLoad__c]){
lstnames.add(new selectOption(objDL.personname__c,objDL.personname__c)); 
}
return lstnames;
}
public String dcountry{get;set;}
public String dcity{get;set;}
public String dph{get;set;}

public String rName{get;set;}
public void populateData(){
try{
DataLoad__c objDL = [select Id,personname__c,city__c,country__c,phone__c from DataLoad__c where personname__c =: rName limit 1];
if(objDL!=null){
dcity=objDL.city__c;
dcountry=objDL.country__c;  
dph = objDL.phone__c;
}
}
catch(Exception e){
dcity='';
dcountry=''; 
dph = '';
}
}
}