src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>fee__c</fullName>
        <label>fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CourseDataDelete.cls
public with sharing class CourseDataDelete {

    public String RID{get;set;}
    public PageReference doDelete() {
        Course__c objDelete = [select Id,fee__c from Course__c where fee__c = 10000];
        delete objDelete;
        return null;
    }

    public List<Course__c> lstcourse = new List<Course__c>();
    public List<Course__c> getRecords() {
        lstcourse = [select Id,name,fee__c from Course__c];
        return lstcourse;
    }
}